### ISSUE TITLE
Chatroom

### ISSUE THREAD

**Issue by mosauter** [mosauter/WT_Battleship#2]
# OPTIONAL
- [x] Chat with others
- [x] maybe with opponent

**Comment by p1206-htwg** [comment]
kurze Info: Entwicklung in branch "chat". Der Chat ist für alle geöffnet.
Der Username vom login könnte evtl. noch mit ausgegeben werden, das dann vielleicht später.
Der Chatroom kann im Moment entweder via path "/chat" oder über die Navbar "chatroom" erreicht werden.

**Comment by p1206-htwg** [comment]
chatrooms can be implemented individually for opponents (see login-issue-comments), however too little time to do that, though that would be a nice feature. For login-system some tasks have yet to be tackled (see relating issue), so we should be ok with this one. Will discuss in exercise lesson.

**Comment by mosauter** [comment]
not implemented yet, maybe in future
