### ISSUE TITLE
Game with AngularJS

### ISSUE THREAD

**Issue by mosauter** [mosauter/WT_Battleship#5]
- [x] representation of field 
- [x] communicate

**Comment by fewieden** [comment]
- [ ] $scope.waiting should be reviewed it's not set correctly everytime it should be set.

**Comment by mosauter** [comment]
Problem is in shoot state there is no waiting message sent if it's not your turn. 

Also waiting is not set in the shoot states in the clients. 

I will fix this later.

**Comment by mosauter** [comment]
Problem is in shoot state there is no waiting message sent if it's not your turn. 


Also waiting is not set in the shoot states in the clients. 


I will fix this later.
