### ISSUE TITLE
Game with Polymer

### ISSUE THREAD

**Issue by mosauter** [mosauter/WT_Battleship#7]

**Comment by p1206-htwg** [comment]
google Maps webcomponent (siehe branch "polymerv2"):
C:\Users\User\workspace\WT_Battleshipv4\project\target\jshint\sbt-jshint-1.0.0.jar:49
                        severity: e.id.substring(1, e.id.length - 1),
                                      ^

TypeError: Cannot read property 'substring' of undefined
    at C:\Users\User\workspace\WT_Battleshipv4\project\target\jshint\sbt-jshint-1.0.0.jar:49:39
    at Array.forEach (native)
    at C:\Users\User\workspace\WT_Battleshipv4\project\target\jshint\sbt-jshint-1.0.0.jar:46:38
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:380:3)

**Comment by p1206-htwg** [comment]
google sign in mit polymer ist ebenfalls ein sehr interessantes Thema für die Präsentation, von dem noch alle was hätten. wir können es einfach als extra page machen, unser spiel muss die Rückgabedaten von dort ja nicht übernehmen . bitte für Mittwoch vormerken :) (die Fehlermeldung von oben besteht nach wie vor)

**Comment by mosauter** [comment]
So no game is implemented but Polymer is used in many cases. For example the Login button in the Navbar is an Polymer Element. Also of course there are components on the /about page and the presentation is build by Polymer.
